<?php

/**
 * Implements hook_menu().
 * 
 * @return array()
 */
function home_work_3_menu() {
  $menu = array();
  
  $menu['upload'] = array(
    'page callback' => 'upload_html',
    'title' => t('Upload files'),
    'access callback' => TRUE,
    'file' => 'home_work_3.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['upload/modal'] = array(
    'page callback' => 'upload_modal_html',
    'title' => t('Upload files'),
    'access callback' => TRUE,
    'file' => 'home_work_3.pages.inc',
    'type' => MENU_CALLBACK,
  );
  
  return $menu;
}

/**
 * Implements hook_init().
 */
function home_work_3_init() {
  drupal_add_css(drupal_get_path('module', 'home_work_3') . '/css/home_work_3.css');
  drupal_add_js(drupal_get_path('module', 'home_work_3') . '/js/script.js');
}

/**
 * Implements hook_file_download
 */
function home_work_3_file_download($uri) {
  global $user;
  
  $file = file_load_multiple(false,array(
    'uri' => $uri,
  ));
  $file = current($file);
  
  $access = FALSE;

  $select = db_select('file_managed', 'fm');
  $select->fields('fm');
  $select->condition('uid', $user->uid);

  $files_data = $select->execute()->fetchAll();
  if(!empty($files_data)) {
    $access = TRUE;
  }
  
  if($access){
    return file_get_content_headers($file);
  }
}